# Generated by Django 5.2.1 on 2025-05-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lijecnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('strucnost', models.CharField(choices=[('psihijatar', 'Psihijatar'), ('psiholog', 'Psiholog'), ('psihoterapeut', 'Psihoterapeut')], max_length=20)),
                ('lokacija', models.CharField(blank=True, max_length=100)),
                ('opis', models.TextField(blank=True, help_text='Kratki opis iskustva ili pristupa liječenju.')),
                ('dostupnost', models.BooleanField(default=True)),
                ('odobren', models.BooleanField(default=False, help_text='Označava je li liječnik verificiran od strane administratora.')),
                ('verifikacijski_dokument', models.FileField(blank=True, help_text='Prenesi dokument koji dokazuje kvalifikacije.', null=True, upload_to='verifikacijski_dokumenti/')),
            ],
        ),
    ]
