# Generated by Django 5.2.1 on 2025-05-28 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0003_alter_lijecnik_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsiholoskiTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('q1', models.IntegerField()),
                ('q2', models.IntegerField()),
                ('q3', models.IntegerField()),
                ('q4', models.IntegerField()),
                ('q5', models.IntegerField()),
                ('q6', models.IntegerField()),
                ('q7', models.IntegerField()),
                ('q8', models.IntegerField()),
                ('q9', models.IntegerField()),
                ('q10', models.IntegerField()),
                ('q11', models.IntegerField()),
                ('q12', models.IntegerField()),
                ('q13', models.IntegerField()),
                ('q14', models.IntegerField()),
                ('q15', models.IntegerField()),
                ('q16', models.IntegerField()),
                ('q17', models.IntegerField()),
                ('q18', models.IntegerField()),
                ('q19', models.IntegerField()),
                ('q20', models.IntegerField()),
                ('q21', models.IntegerField()),
                ('q22', models.IntegerField()),
                ('q23', models.IntegerField()),
                ('q24', models.IntegerField()),
                ('q25', models.IntegerField()),
                ('q26', models.IntegerField()),
                ('q27', models.IntegerField()),
                ('q28', models.IntegerField()),
                ('q29', models.IntegerField()),
                ('q30', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
