# Generated by Django 5.2.1 on 2025-05-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0004_psiholoskitest'),
    ]

    operations = [
        migrations.AddField(
            model_name='psiholoskitest',
            name='predikcija',
            field=models.CharField(default='Nema poremećaja', max_length=50),
        ),
    ]
