# Generated by Django 5.2.1 on 2025-05-31 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0005_psiholoskitest_predikcija'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poruka', models.TextField()),
                ('procitano', models.BooleanField(default=False)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikacije', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ponuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('poruka', models.TextField()),
                ('klijent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primljene_ponude', to=settings.AUTH_USER_MODEL)),
                ('lijecnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poslane_ponude', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
