# Generated by Django 5.2.1 on 2025-06-02 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0007_notifikacija_lijecnik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPoruka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField()),
                ('vreme', models.DateTimeField(auto_now_add=True)),
                ('posiljalac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poslane_poruke', to=settings.AUTH_USER_MODEL)),
                ('primalac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primljene_poruke', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
